<a href="https://colab.research.google.com/github/remre/StriveSchool-ai/blob/main/week2/sol/72_75_numpy_sol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
import numpy as np
def swap(x,y):
  a= np.random.randint(20,size=(5,5))
  print(a)
  if x or y > 6 :
    print("give me something between 0,5 ")
  elif x==y:
    print("the value of x and y must be different")
  else:
      a[[x,y]]=a[[y,x]]
      return a
swap(4,3)

[[ 7  5  7  4 19]
 [ 0  8 18  5  2]
 [ 1  8 14 14 19]
 [ 1 15 16 12 18]
 [10 15 14  7  4]]
give me something between 0,5 


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [29]:
arr = np.array([1,2,3,3,4,56,7])
arr = np.cumsum(arr)/(arr.size)
arr

array([ 0.14285714,  0.42857143,  0.85714286,  1.28571429,  1.85714286,
        9.85714286, 10.85714286])